### ISSUE TITLE
Separate .allowed-licences for require and require-dev

### ISSUE THREAD

**Issue by codegain** [madewithlove/license-checker-php#25]
Hi,

I was thinking if it would be possible to have different `.allowed-licences` files for the `require` and `require-dev` section of the `composer.json` for better control.

For example: Usage of a GPL package is allowed, but only if the package is defined in `require-dev` (like packages used for code style checks which will not be distributed).

**Comment by jdrieghe** [comment]
@codegain That's an interesting idea. I'll look into it and will get back to you on this.

**Comment by jdrieghe** [comment]
@codegain We added some CLI options to pass `--no-dev` and a custom config `--filename`. Combining these should make it possible to solve what you suggested. Once this gets reviewed tomorrow morning I'm aiming to release a new minor version.
What do you think?

**Comment by jdrieghe** [comment]
We published a new release to resolve this here: https://github.com/madewithlove/license-checker-php/releases/tag/v1.1
If this doesn't fully cover the needs, feel free to open a new issue.

Thanks for the idea and feedback!

**Comment by codegain** [comment]
@jdrieghe Hi, any chance this could be backported to the 0.10 release? I'm currently not able to update to PHP 8 just yet.

**Comment by jdrieghe** [comment]
@codegain If you feel like creating a PR for this I would be happy to add a separate branch for `0.x` based on the `0.10` release. You can probably recycle most of the changes from the `main` branch. However, I would rather not spend too much time on maintaining the older version myself.

**Comment by jdrieghe** [comment]
Alternatively, I think it's possible to run the CI pipeline checks against a PHP 8 container. The application does not need to be PHP 8 compatible itself, it only needs to be able to install the dependencies (maybe using `--ignore-platform-req=php`?)
